import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import { AiOutlineFile, AiOutlineDelete } from "react-icons/ai";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="p-6 space-y-5 w-[650px]">
          <div className="flex items-center justify-between">
            <div className="space-y-1">
              <h1 className="text-3xl font-semibold">
                [Contoh] Sistem Restoran
              </h1>
              <p className="text-muted-foreground text-sm">
                Ambisius Coding Challenge #230916H
              </p>
            </div>
            <button>
              <div className="border rounded-full p-4 hover:bg-muted transition-colors cursor-pointer bg-background shadow">
                <AiOutlineFile />
              </div>
            </button>
          </div>
          <div dir="ltr" data-orientation="horizontal">
            <Navbar />
            <div className="px-6 py-4 mt-4 bg-muted rounded-md min-h-[300px]">
              {children}
            </div>
          </div>
          <p className="text-sm text-muted-foreground text-center">
            Semua data disimpan di Local Storage Browser
          </p>
        </main>
      </body>
    </html>
  );
}
